#
#   OpenWeatherMap Variables
#
weather_api_key: "YOUR_KEY_HERE"

#
#   Twitter Variables
#
twitter_consumer_key: "YOUR_KEY_HERE"
twitter_consumer_secret: "YOUR_KEY_HERE"
twitter_access_token: "YOUR_KEY_HERE"
twitter_access_token_secret: "YOUR_KEY_HERE"